G++PXA = arm-unknown-linux-gnu-g++ 
all:
	g++ -std=c++11 -o overcook overcook.cpp
	g++pxa -o arm_overcook overcook.cpp
window:
	g++ -std=c++11 -o overcook overcook.cpp
pxa:
	g++pxa  -o arm_overcook overcook.cpp
clean:
	rm overcook
